#!/bin/bash
# Colored, pluggable PS1
#
# Copyright (C) 2013, 2014 LoVullo Associates, Inc.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# default hookable values
declare ps1_pre=
declare ps1_body='\[\033[00;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]'
declare ps1_pre_end=
declare ps1_end='$ '

# we update the PS1 in this manner to permit executing commands that output PS1
# escape sequences
update-ps1()
{
  # Debian default color prompt, sans chroot output; do not perform capibility
  # checks, since all used terminals support color
  PS1="${ps1_pre}${ps1_body}${ps1_pre_end}${ps1_end}"
}

# scripts may use to recognize that the pluggable PS1 has been loaded
declare -r ps1_pluggable=1
update-ps1

