#!/bin/bash
# Obnoxiously tall PS1, similar to that of msysgit
#
# Copyright (C) 2013, 2014 LoVullo Associates, Inc.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# we would be wise not to inflict this upon innocent users unless explicitly
# requested!
if enabled && [ "$ps1_pluggable" -eq 1 ]; then
  ps1_pre=$'\n'"$PS1_PRE"
  ps1_end=$'\n'"$PS1_END"
  update-ps1
fi

